module.exports = {
  darkMode: 'class',
  content: ['./App.tsx', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        heading: ['DMSans-Bold'],
        body: ['DMSans-Regular'],
        mono: ['JetBrainsMono-Regular'],
        //weights
        thin: ['DMSans-Thin'],
        extralight: ['DMSans-ExtraLight'],
        light: ['DMSans-Light'],
        normal: ['DMSans-Regular'],
        regular: ['DMSans-Regular'],
        medium: ['DMSans-Medium'],
        semibold: ['DMSans-SemiBold'],
        bold: ['DMSans-Bold'],
        extrabold: ['DMSans-ExtraBold'],
        bblack: ['DMSans-Black'], //bblack
        //styles
        'thin-italic': ['DMSans-ThinItalic'],
        'extralight-italic': ['DMSans-ExtraLightItalic'],
        'light-italic': ['DMSans-LightItalic'],
        italic: ['DMSans-RegularItalic'],
        'body-italic': ['DMSans-RegularItalic'],
        'regular-italic': ['DMSans-RegularItalic'],
        'normal-italic': ['DMSans-RegularItalic'],
        'medium-italic': ['DMSans-MediumItalic'],
        'semibold-italic': ['DMSans-SemiBoldItalic'],
        'bold-italic': ['DMSans-BoldItalic'],
        'heading-italic': ['DMSans-BoldItalic'],
        'extrabold-italic': ['DMSans-ExtraBoldItalic'],
        'bblack-italic': ['DMSans-BlackItalic'],
      },
      fontWeight: {
        thin: 'normal',
        extraLight: 'normal',
        light: 'normal',
        medium: 'normal',
        semibold: 'normal',
        bold: 'normal',
        extrabold: 'normal',
        black: 'normal',
      },
      fontStyle: {
        normal: 'normal',
        italic: 'normal',
      },
      colors: {
        semantic: {
          playtime: {
            0: 'rgb(var(--color-semantic-playtime-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-playtime-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-playtime-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-playtime-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-playtime-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-playtime-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-playtime-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-playtime-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-playtime-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-playtime-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-playtime-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-playtime-950)/<alpha-value>)',
          },
          lastPlayed: {
            0: 'rgb(var(--color-semantic-lastPlayed-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-lastPlayed-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-lastPlayed-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-lastPlayed-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-lastPlayed-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-lastPlayed-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-lastPlayed-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-lastPlayed-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-lastPlayed-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-lastPlayed-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-lastPlayed-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-lastPlayed-950)/<alpha-value>)',
          },
          genre: {
            0: 'rgb(var(--color-semantic-genre-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-genre-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-genre-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-genre-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-genre-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-genre-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-genre-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-genre-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-genre-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-genre-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-genre-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-genre-950)/<alpha-value>)',
          },
          maxPerDay: {
            0: 'rgb(var(--color-semantic-maxPerDay-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-maxPerDay-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-maxPerDay-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-maxPerDay-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-maxPerDay-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-maxPerDay-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-maxPerDay-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-maxPerDay-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-maxPerDay-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-maxPerDay-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-maxPerDay-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-maxPerDay-950)/<alpha-value>)',
          },
          gameStreak: {
            0: 'rgb(var(--color-semantic-gameStreak-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-gameStreak-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-gameStreak-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-gameStreak-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-gameStreak-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-gameStreak-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-gameStreak-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-gameStreak-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-gameStreak-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-gameStreak-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-gameStreak-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-gameStreak-950)/<alpha-value>)',
          },
          dayStreak: {
            0: 'rgb(var(--color-semantic-dayStreak-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-dayStreak-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-dayStreak-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-dayStreak-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-dayStreak-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-dayStreak-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-dayStreak-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-dayStreak-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-dayStreak-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-dayStreak-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-dayStreak-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-dayStreak-950)/<alpha-value>)',
          },
          topPlatform: {
            0: 'rgb(var(--color-semantic-topPlatform-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-topPlatform-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-topPlatform-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-topPlatform-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-topPlatform-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-topPlatform-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-topPlatform-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-topPlatform-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-topPlatform-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-topPlatform-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-topPlatform-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-topPlatform-950)/<alpha-value>)',
          },
        },
        comparison: {
          user: {
            0: 'rgb(var(--color-primary-0)/<alpha-value>)',
            50: 'rgb(var(--color-primary-50)/<alpha-value>)',
            100: 'rgb(var(--color-primary-100)/<alpha-value>)',
            200: 'rgb(var(--color-primary-200)/<alpha-value>)',
            300: 'rgb(var(--color-primary-300)/<alpha-value>)',
            400: 'rgb(var(--color-primary-400)/<alpha-value>)',
            500: 'rgb(var(--color-primary-500)/<alpha-value>)',
            600: 'rgb(var(--color-primary-600)/<alpha-value>)',
            700: 'rgb(var(--color-primary-700)/<alpha-value>)',
            800: 'rgb(var(--color-primary-800)/<alpha-value>)',
            900: 'rgb(var(--color-primary-900)/<alpha-value>)',
            950: 'rgb(var(--color-primary-950)/<alpha-value>)',
          },
          compare: {
            0: 'rgb(var(--color-semantic-comparison-compare-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-comparison-compare-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-comparison-compare-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-comparison-compare-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-comparison-compare-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-comparison-compare-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-comparison-compare-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-comparison-compare-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-comparison-compare-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-comparison-compare-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-comparison-compare-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-comparison-compare-950)/<alpha-value>)',
          },
        },
        gameStatus: {
          playing: {
            0: 'rgb(var(--color-semantic-gameStatus-playing-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-gameStatus-playing-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-gameStatus-playing-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-gameStatus-playing-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-gameStatus-playing-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-gameStatus-playing-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-gameStatus-playing-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-gameStatus-playing-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-gameStatus-playing-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-gameStatus-playing-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-gameStatus-playing-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-gameStatus-playing-950)/<alpha-value>)',
          },
          toBePlayed: {
            0: 'rgb(var(--color-semantic-gameStatus-toBePlayed-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-gameStatus-toBePlayed-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-gameStatus-toBePlayed-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-gameStatus-toBePlayed-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-gameStatus-toBePlayed-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-gameStatus-toBePlayed-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-gameStatus-toBePlayed-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-gameStatus-toBePlayed-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-gameStatus-toBePlayed-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-gameStatus-toBePlayed-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-gameStatus-toBePlayed-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-gameStatus-toBePlayed-950)/<alpha-value>)',
          },
          platinato: {
            0: 'rgb(var(--color-semantic-gameStatus-platinato-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-gameStatus-platinato-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-gameStatus-platinato-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-gameStatus-platinato-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-gameStatus-platinato-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-gameStatus-platinato-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-gameStatus-platinato-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-gameStatus-platinato-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-gameStatus-platinato-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-gameStatus-platinato-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-gameStatus-platinato-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-gameStatus-platinato-950)/<alpha-value>)',
          },
          shelved: {
            0: 'rgb(var(--color-semantic-gameStatus-shelved-0)/<alpha-value>)',
            50: 'rgb(var(--color-semantic-gameStatus-shelved-50)/<alpha-value>)',
            100: 'rgb(var(--color-semantic-gameStatus-shelved-100)/<alpha-value>)',
            200: 'rgb(var(--color-semantic-gameStatus-shelved-200)/<alpha-value>)',
            300: 'rgb(var(--color-semantic-gameStatus-shelved-300)/<alpha-value>)',
            400: 'rgb(var(--color-semantic-gameStatus-shelved-400)/<alpha-value>)',
            500: 'rgb(var(--color-semantic-gameStatus-shelved-500)/<alpha-value>)',
            600: 'rgb(var(--color-semantic-gameStatus-shelved-600)/<alpha-value>)',
            700: 'rgb(var(--color-semantic-gameStatus-shelved-700)/<alpha-value>)',
            800: 'rgb(var(--color-semantic-gameStatus-shelved-800)/<alpha-value>)',
            900: 'rgb(var(--color-semantic-gameStatus-shelved-900)/<alpha-value>)',
            950: 'rgb(var(--color-semantic-gameStatus-shelved-950)/<alpha-value>)',
          },
        },

        primary: {
          0: 'rgb(var(--color-primary-0)/<alpha-value>)',
          50: 'rgb(var(--color-primary-50)/<alpha-value>)',
          100: 'rgb(var(--color-primary-100)/<alpha-value>)',
          200: 'rgb(var(--color-primary-200)/<alpha-value>)',
          300: 'rgb(var(--color-primary-300)/<alpha-value>)',
          400: 'rgb(var(--color-primary-400)/<alpha-value>)',
          500: 'rgb(var(--color-primary-500)/<alpha-value>)',
          600: 'rgb(var(--color-primary-600)/<alpha-value>)',
          700: 'rgb(var(--color-primary-700)/<alpha-value>)',
          800: 'rgb(var(--color-primary-800)/<alpha-value>)',
          900: 'rgb(var(--color-primary-900)/<alpha-value>)',
          950: 'rgb(var(--color-primary-950)/<alpha-value>)',
        },
        secondary: {
          0: 'rgb(var(--color-secondary-0)/<alpha-value>)',
          50: 'rgb(var(--color-secondary-50)/<alpha-value>)',
          100: 'rgb(var(--color-secondary-100)/<alpha-value>)',
          200: 'rgb(var(--color-secondary-200)/<alpha-value>)',
          300: 'rgb(var(--color-secondary-300)/<alpha-value>)',
          400: 'rgb(var(--color-secondary-400)/<alpha-value>)',
          500: 'rgb(var(--color-secondary-500)/<alpha-value>)',
          600: 'rgb(var(--color-secondary-600)/<alpha-value>)',
          700: 'rgb(var(--color-secondary-700)/<alpha-value>)',
          800: 'rgb(var(--color-secondary-800)/<alpha-value>)',
          900: 'rgb(var(--color-secondary-900)/<alpha-value>)',
          950: 'rgb(var(--color-secondary-950)/<alpha-value>)',
        },
        tertiary: {
          50: 'rgb(var(--color-tertiary-50)/<alpha-value>)',
          100: 'rgb(var(--color-tertiary-100)/<alpha-value>)',
          200: 'rgb(var(--color-tertiary-200)/<alpha-value>)',
          300: 'rgb(var(--color-tertiary-300)/<alpha-value>)',
          400: 'rgb(var(--color-tertiary-400)/<alpha-value>)',
          500: 'rgb(var(--color-tertiary-500)/<alpha-value>)',
          600: 'rgb(var(--color-tertiary-600)/<alpha-value>)',
          700: 'rgb(var(--color-tertiary-700)/<alpha-value>)',
          800: 'rgb(var(--color-tertiary-800)/<alpha-value>)',
          900: 'rgb(var(--color-tertiary-900)/<alpha-value>)',
          950: 'rgb(var(--color-tertiary-950)/<alpha-value>)',
        },
        error: {
          0: 'rgb(var(--color-error-0)/<alpha-value>)',
          50: 'rgb(var(--color-error-50)/<alpha-value>)',
          100: 'rgb(var(--color-error-100)/<alpha-value>)',
          200: 'rgb(var(--color-error-200)/<alpha-value>)',
          300: 'rgb(var(--color-error-300)/<alpha-value>)',
          400: 'rgb(var(--color-error-400)/<alpha-value>)',
          500: 'rgb(var(--color-error-500)/<alpha-value>)',
          600: 'rgb(var(--color-error-600)/<alpha-value>)',
          700: 'rgb(var(--color-error-700)/<alpha-value>)',
          800: 'rgb(var(--color-error-800)/<alpha-value>)',
          900: 'rgb(var(--color-error-900)/<alpha-value>)',
          950: 'rgb(var(--color-error-950)/<alpha-value>)',
        },
        success: {
          0: 'rgb(var(--color-success-0)/<alpha-value>)',
          50: 'rgb(var(--color-success-50)/<alpha-value>)',
          100: 'rgb(var(--color-success-100)/<alpha-value>)',
          200: 'rgb(var(--color-success-200)/<alpha-value>)',
          300: 'rgb(var(--color-success-300)/<alpha-value>)',
          400: 'rgb(var(--color-success-400)/<alpha-value>)',
          500: 'rgb(var(--color-success-500)/<alpha-value>)',
          600: 'rgb(var(--color-success-600)/<alpha-value>)',
          700: 'rgb(var(--color-success-700)/<alpha-value>)',
          800: 'rgb(var(--color-success-800)/<alpha-value>)',
          900: 'rgb(var(--color-success-900)/<alpha-value>)',
          950: 'rgb(var(--color-success-950)/<alpha-value>)',
        },
        warning: {
          0: 'rgb(var(--color-warning-0)/<alpha-value>)',
          50: 'rgb(var(--color-warning-50)/<alpha-value>)',
          100: 'rgb(var(--color-warning-100)/<alpha-value>)',
          200: 'rgb(var(--color-warning-200)/<alpha-value>)',
          300: 'rgb(var(--color-warning-300)/<alpha-value>)',
          400: 'rgb(var(--color-warning-400)/<alpha-value>)',
          500: 'rgb(var(--color-warning-500)/<alpha-value>)',
          600: 'rgb(var(--color-warning-600)/<alpha-value>)',
          700: 'rgb(var(--color-warning-700)/<alpha-value>)',
          800: 'rgb(var(--color-warning-800)/<alpha-value>)',
          900: 'rgb(var(--color-warning-900)/<alpha-value>)',
          950: 'rgb(var(--color-warning-950)/<alpha-value>)',
        },
        info: {
          0: 'rgb(var(--color-info-0)/<alpha-value>)',
          50: 'rgb(var(--color-info-50)/<alpha-value>)',
          100: 'rgb(var(--color-info-100)/<alpha-value>)',
          200: 'rgb(var(--color-info-200)/<alpha-value>)',
          300: 'rgb(var(--color-info-300)/<alpha-value>)',
          400: 'rgb(var(--color-info-400)/<alpha-value>)',
          500: 'rgb(var(--color-info-500)/<alpha-value>)',
          600: 'rgb(var(--color-info-600)/<alpha-value>)',
          700: 'rgb(var(--color-info-700)/<alpha-value>)',
          800: 'rgb(var(--color-info-800)/<alpha-value>)',
          900: 'rgb(var(--color-info-900)/<alpha-value>)',
          950: 'rgb(var(--color-info-950)/<alpha-value>)',
        },
        typography: {
          0: 'rgb(var(--color-typography-0)/<alpha-value>)',
          50: 'rgb(var(--color-typography-50)/<alpha-value>)',
          100: 'rgb(var(--color-typography-100)/<alpha-value>)',
          200: 'rgb(var(--color-typography-200)/<alpha-value>)',
          300: 'rgb(var(--color-typography-300)/<alpha-value>)',
          400: 'rgb(var(--color-typography-400)/<alpha-value>)',
          500: 'rgb(var(--color-typography-500)/<alpha-value>)',
          600: 'rgb(var(--color-typography-600)/<alpha-value>)',
          700: 'rgb(var(--color-typography-700)/<alpha-value>)',
          800: 'rgb(var(--color-typography-800)/<alpha-value>)',
          900: 'rgb(var(--color-typography-900)/<alpha-value>)',
          950: 'rgb(var(--color-typography-950)/<alpha-value>)',
          white: '#FFFFFF',
          gray: '#D4D4D4',
          black: '#181718',
        },
        outline: {
          0: 'rgb(var(--color-outline-0)/<alpha-value>)',
          50: 'rgb(var(--color-outline-50)/<alpha-value>)',
          100: 'rgb(var(--color-outline-100)/<alpha-value>)',
          200: 'rgb(var(--color-outline-200)/<alpha-value>)',
          300: 'rgb(var(--color-outline-300)/<alpha-value>)',
          400: 'rgb(var(--color-outline-400)/<alpha-value>)',
          500: 'rgb(var(--color-outline-500)/<alpha-value>)',
          600: 'rgb(var(--color-outline-600)/<alpha-value>)',
          700: 'rgb(var(--color-outline-700)/<alpha-value>)',
          800: 'rgb(var(--color-outline-800)/<alpha-value>)',
          900: 'rgb(var(--color-outline-900)/<alpha-value>)',
          950: 'rgb(var(--color-outline-950)/<alpha-value>)',
        },
        background: {
          0: 'rgb(var(--color-background-0)/<alpha-value>)',
          50: 'rgb(var(--color-background-50)/<alpha-value>)',
          100: 'rgb(var(--color-background-100)/<alpha-value>)',
          200: 'rgb(var(--color-background-200)/<alpha-value>)',
          300: 'rgb(var(--color-background-300)/<alpha-value>)',
          400: 'rgb(var(--color-background-400)/<alpha-value>)',
          500: 'rgb(var(--color-background-500)/<alpha-value>)',
          600: 'rgb(var(--color-background-600)/<alpha-value>)',
          700: 'rgb(var(--color-background-700)/<alpha-value>)',
          800: 'rgb(var(--color-background-800)/<alpha-value>)',
          900: 'rgb(var(--color-background-900)/<alpha-value>)',
          950: 'rgb(var(--color-background-950)/<alpha-value>)',
          error: 'rgb(var(--color-background-error)/<alpha-value>)',
          warning: 'rgb(var(--color-background-warning)/<alpha-value>)',
          muted: 'rgb(var(--color-background-muted)/<alpha-value>)',
          success: 'rgb(var(--color-background-success)/<alpha-value>)',
          info: 'rgb(var(--color-background-info)/<alpha-value>)',
          light: '#FBFBFB',
          dark: '#181719',
        },
        indicator: {
          primary: 'rgb(var(--color-indicator-primary)/<alpha-value>)',
          info: 'rgb(var(--color-indicator-info)/<alpha-value>)',
          error: 'rgb(var(--color-indicator-error)/<alpha-value>)',
        },
      },
      boxShadow: {
        'hard-1': '-2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-2': '0px 3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-3': '2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-4': '0px -3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-5': '0px 2px 10px 0px rgba(38, 38, 38, 0.10)',
        'soft-1': '0px 0px 10px rgba(38, 38, 38, 0.1)',
        'soft-2': '0px 0px 20px rgba(38, 38, 38, 0.2)',
        'soft-3': '0px 0px 30px rgba(38, 38, 38, 0.1)',
        'soft-4': '0px 0px 40px rgba(38, 38, 38, 0.1)',
      },
    },
  },
};
