'use client';
import { vars } from 'nativewind';
import { tailwindColors, brand } from '@gamelog/theme/theme';

export const commonColors = {
  // Semantic Tokens
  '--color-semantic-playtime-0': brand.semantic.playtime[0],
  '--color-semantic-playtime-50': brand.semantic.playtime[50],
  '--color-semantic-playtime-100': brand.semantic.playtime[100],
  '--color-semantic-playtime-200': brand.semantic.playtime[200],
  '--color-semantic-playtime-300': brand.semantic.playtime[300],
  '--color-semantic-playtime-400': brand.semantic.playtime[400],
  '--color-semantic-playtime-500': brand.semantic.playtime[500],
  '--color-semantic-playtime-600': brand.semantic.playtime[600],
  '--color-semantic-playtime-700': brand.semantic.playtime[700],
  '--color-semantic-playtime-800': brand.semantic.playtime[800],
  '--color-semantic-playtime-900': brand.semantic.playtime[900],
  '--color-semantic-playtime-950': brand.semantic.playtime[950],
  '--color-semantic-lastPlayed-0': brand.semantic.lastPlayed[0],
  '--color-semantic-lastPlayed-50': brand.semantic.lastPlayed[50],
  '--color-semantic-lastPlayed-100': brand.semantic.lastPlayed[100],
  '--color-semantic-lastPlayed-200': brand.semantic.lastPlayed[200],
  '--color-semantic-lastPlayed-300': brand.semantic.lastPlayed[300],
  '--color-semantic-lastPlayed-400': brand.semantic.lastPlayed[400],
  '--color-semantic-lastPlayed-500': brand.semantic.lastPlayed[500],
  '--color-semantic-lastPlayed-600': brand.semantic.lastPlayed[600],
  '--color-semantic-lastPlayed-700': brand.semantic.lastPlayed[700],
  '--color-semantic-lastPlayed-800': brand.semantic.lastPlayed[800],
  '--color-semantic-lastPlayed-900': brand.semantic.lastPlayed[900],
  '--color-semantic-lastPlayed-950': brand.semantic.lastPlayed[950],
  '--color-semantic-genre-0': brand.semantic.genre[0],
  '--color-semantic-genre-50': brand.semantic.genre[50],
  '--color-semantic-genre-100': brand.semantic.genre[100],
  '--color-semantic-genre-200': brand.semantic.genre[200],
  '--color-semantic-genre-300': brand.semantic.genre[300],
  '--color-semantic-genre-400': brand.semantic.genre[400],
  '--color-semantic-genre-500': brand.semantic.genre[500],
  '--color-semantic-genre-600': brand.semantic.genre[600],
  '--color-semantic-genre-700': brand.semantic.genre[700],
  '--color-semantic-genre-800': brand.semantic.genre[800],
  '--color-semantic-genre-900': brand.semantic.genre[900],
  '--color-semantic-genre-950': brand.semantic.genre[950],
  '--color-semantic-maxPerDay-0': brand.semantic.maxPerDay[0],
  '--color-semantic-maxPerDay-50': brand.semantic.maxPerDay[50],
  '--color-semantic-maxPerDay-100': brand.semantic.maxPerDay[100],
  '--color-semantic-maxPerDay-200': brand.semantic.maxPerDay[200],
  '--color-semantic-maxPerDay-300': brand.semantic.maxPerDay[300],
  '--color-semantic-maxPerDay-400': brand.semantic.maxPerDay[400],
  '--color-semantic-maxPerDay-500': brand.semantic.maxPerDay[500],
  '--color-semantic-maxPerDay-600': brand.semantic.maxPerDay[600],
  '--color-semantic-maxPerDay-700': brand.semantic.maxPerDay[700],
  '--color-semantic-maxPerDay-800': brand.semantic.maxPerDay[800],
  '--color-semantic-maxPerDay-900': brand.semantic.maxPerDay[900],
  '--color-semantic-maxPerDay-950': brand.semantic.maxPerDay[950],
  '--color-semantic-gameStreak-0': brand.semantic.gameStreak[0],
  '--color-semantic-gameStreak-50': brand.semantic.gameStreak[50],
  '--color-semantic-gameStreak-100': brand.semantic.gameStreak[100],
  '--color-semantic-gameStreak-200': brand.semantic.gameStreak[200],
  '--color-semantic-gameStreak-300': brand.semantic.gameStreak[300],
  '--color-semantic-gameStreak-400': brand.semantic.gameStreak[400],
  '--color-semantic-gameStreak-500': brand.semantic.gameStreak[500],
  '--color-semantic-gameStreak-600': brand.semantic.gameStreak[600],
  '--color-semantic-gameStreak-700': brand.semantic.gameStreak[700],
  '--color-semantic-gameStreak-800': brand.semantic.gameStreak[800],
  '--color-semantic-gameStreak-900': brand.semantic.gameStreak[900],
  '--color-semantic-gameStreak-950': brand.semantic.gameStreak[950],
  '--color-semantic-dayStreak-0': brand.semantic.dayStreak[0],
  '--color-semantic-dayStreak-50': brand.semantic.dayStreak[50],
  '--color-semantic-dayStreak-100': brand.semantic.dayStreak[100],
  '--color-semantic-dayStreak-200': brand.semantic.dayStreak[200],
  '--color-semantic-dayStreak-300': brand.semantic.dayStreak[300],
  '--color-semantic-dayStreak-400': brand.semantic.dayStreak[400],
  '--color-semantic-dayStreak-500': brand.semantic.dayStreak[500],
  '--color-semantic-dayStreak-600': brand.semantic.dayStreak[600],
  '--color-semantic-dayStreak-700': brand.semantic.dayStreak[700],
  '--color-semantic-dayStreak-800': brand.semantic.dayStreak[800],
  '--color-semantic-dayStreak-900': brand.semantic.dayStreak[900],
  '--color-semantic-dayStreak-950': brand.semantic.dayStreak[950],
  '--color-semantic-topPlatform-0': brand.semantic.topPlatform[0],
  '--color-semantic-topPlatform-50': brand.semantic.topPlatform[50],
  '--color-semantic-topPlatform-100': brand.semantic.topPlatform[100],
  '--color-semantic-topPlatform-200': brand.semantic.topPlatform[200],
  '--color-semantic-topPlatform-300': brand.semantic.topPlatform[300],
  '--color-semantic-topPlatform-400': brand.semantic.topPlatform[400],
  '--color-semantic-topPlatform-500': brand.semantic.topPlatform[500],
  '--color-semantic-topPlatform-600': brand.semantic.topPlatform[600],
  '--color-semantic-topPlatform-700': brand.semantic.topPlatform[700],
  '--color-semantic-topPlatform-800': brand.semantic.topPlatform[800],
  '--color-semantic-topPlatform-900': brand.semantic.topPlatform[900],
  '--color-semantic-topPlatform-950': brand.semantic.topPlatform[950],
  '--color-semantic-comparison-compare-0': brand.semantic.topPlatform[0],
  '--color-semantic-comparison-compare-50': brand.semantic.topPlatform[50],
  '--color-semantic-comparison-compare-100': brand.semantic.topPlatform[100],
  '--color-semantic-comparison-compare-200': brand.semantic.topPlatform[200],
  '--color-semantic-comparison-compare-300': brand.semantic.topPlatform[300],
  '--color-semantic-comparison-compare-400': brand.semantic.topPlatform[400],
  '--color-semantic-comparison-compare-500': brand.semantic.topPlatform[500],
  '--color-semantic-comparison-compare-600': brand.semantic.topPlatform[600],
  '--color-semantic-comparison-compare-700': brand.semantic.topPlatform[700],
  '--color-semantic-comparison-compare-800': brand.semantic.topPlatform[800],
  '--color-semantic-comparison-compare-900': brand.semantic.topPlatform[900],
  '--color-semantic-comparison-compare-950': brand.semantic.topPlatform[950],

  // Game Status Tokens
  '--color-semantic-gameStatus-playing-0': brand.gameStatus.playing[0],
  '--color-semantic-gameStatus-playing-50': brand.gameStatus.playing[50],
  '--color-semantic-gameStatus-playing-100': brand.gameStatus.playing[100],
  '--color-semantic-gameStatus-playing-200': brand.gameStatus.playing[200],
  '--color-semantic-gameStatus-playing-300': brand.gameStatus.playing[300],
  '--color-semantic-gameStatus-playing-400': brand.gameStatus.playing[400],
  '--color-semantic-gameStatus-playing-500': brand.gameStatus.playing[500],
  '--color-semantic-gameStatus-playing-600': brand.gameStatus.playing[600],
  '--color-semantic-gameStatus-playing-700': brand.gameStatus.playing[700],
  '--color-semantic-gameStatus-playing-800': brand.gameStatus.playing[800],
  '--color-semantic-gameStatus-playing-900': brand.gameStatus.playing[900],
  '--color-semantic-gameStatus-playing-950': brand.gameStatus.playing[950],
  '--color-semantic-gameStatus-toBePlayed-0': brand.gameStatus.toBePlayed[0],
  '--color-semantic-gameStatus-toBePlayed-50': brand.gameStatus.toBePlayed[50],
  '--color-semantic-gameStatus-toBePlayed-100': brand.gameStatus.toBePlayed[100],
  '--color-semantic-gameStatus-toBePlayed-200': brand.gameStatus.toBePlayed[200],
  '--color-semantic-gameStatus-toBePlayed-300': brand.gameStatus.toBePlayed[300],
  '--color-semantic-gameStatus-toBePlayed-400': brand.gameStatus.toBePlayed[400],
  '--color-semantic-gameStatus-toBePlayed-500': brand.gameStatus.toBePlayed[500],
  '--color-semantic-gameStatus-toBePlayed-600': brand.gameStatus.toBePlayed[600],
  '--color-semantic-gameStatus-toBePlayed-700': brand.gameStatus.toBePlayed[700],
  '--color-semantic-gameStatus-toBePlayed-800': brand.gameStatus.toBePlayed[800],
  '--color-semantic-gameStatus-toBePlayed-900': brand.gameStatus.toBePlayed[900],
  '--color-semantic-gameStatus-toBePlayed-950': brand.gameStatus.toBePlayed[950],
  '--color-semantic-gameStatus-platinato-0': brand.gameStatus.platinato[0],
  '--color-semantic-gameStatus-platinato-50': brand.gameStatus.platinato[50],
  '--color-semantic-gameStatus-platinato-100': brand.gameStatus.platinato[100],
  '--color-semantic-gameStatus-platinato-200': brand.gameStatus.platinato[200],
  '--color-semantic-gameStatus-platinato-300': brand.gameStatus.platinato[300],
  '--color-semantic-gameStatus-platinato-400': brand.gameStatus.platinato[400],
  '--color-semantic-gameStatus-platinato-500': brand.gameStatus.platinato[500],
  '--color-semantic-gameStatus-platinato-600': brand.gameStatus.platinato[600],
  '--color-semantic-gameStatus-platinato-700': brand.gameStatus.platinato[700],
  '--color-semantic-gameStatus-platinato-800': brand.gameStatus.platinato[800],
  '--color-semantic-gameStatus-platinato-900': brand.gameStatus.platinato[900],
  '--color-semantic-gameStatus-platinato-950': brand.gameStatus.platinato[950],
  '--color-semantic-gameStatus-shelved-0': brand.gameStatus.shelved[0],
  '--color-semantic-gameStatus-shelved-50': brand.gameStatus.shelved[50],
  '--color-semantic-gameStatus-shelved-100': brand.gameStatus.shelved[100],
  '--color-semantic-gameStatus-shelved-200': brand.gameStatus.shelved[200],
  '--color-semantic-gameStatus-shelved-300': brand.gameStatus.shelved[300],
  '--color-semantic-gameStatus-shelved-400': brand.gameStatus.shelved[400],
  '--color-semantic-gameStatus-shelved-500': brand.gameStatus.shelved[500],
  '--color-semantic-gameStatus-shelved-600': brand.gameStatus.shelved[600],
  '--color-semantic-gameStatus-shelved-700': brand.gameStatus.shelved[700],
  '--color-semantic-gameStatus-shelved-800': brand.gameStatus.shelved[800],
  '--color-semantic-gameStatus-shelved-900': brand.gameStatus.shelved[900],
  '--color-semantic-gameStatus-shelved-950': brand.gameStatus.shelved[950],

  '--color-success-0': brand.success[0],
  '--color-success-50': brand.success[50],
  '--color-success-100': brand.success[100],
  '--color-success-200': brand.success[200],
  '--color-success-300': brand.success[300],
  '--color-success-400': brand.success[400],
  '--color-success-500': brand.success[500],
  '--color-success-600': brand.success[600],
  '--color-success-700': brand.success[700],
  '--color-success-800': brand.success[800],
  '--color-success-900': brand.success[900],
  '--color-success-950': brand.success[950],

  '--color-warning-0': brand.warning[0],
  '--color-warning-50': brand.warning[50],
  '--color-warning-100': brand.warning[100],
  '--color-warning-200': brand.warning[200],
  '--color-warning-300': brand.warning[300],
  '--color-warning-400': brand.warning[400],
  '--color-warning-500': brand.warning[500],
  '--color-warning-600': brand.warning[600],
  '--color-warning-700': brand.warning[700],
  '--color-warning-800': brand.warning[800],
  '--color-warning-900': brand.warning[900],
  '--color-warning-950': brand.warning[950],

  '--color-error-0': brand.error[0],
  '--color-error-50': brand.error[50],
  '--color-error-100': brand.error[100],
  '--color-error-200': brand.error[200],
  '--color-error-300': brand.error[300],
  '--color-error-400': brand.error[400],
  '--color-error-500': brand.error[500],
  '--color-error-600': brand.error[600],
  '--color-error-700': brand.error[700],
  '--color-error-800': brand.error[800],
  '--color-error-900': brand.error[900],
  '--color-error-950': brand.error[950],

  '--color-info-0': brand.info[0],
  '--color-info-50': brand.info[50],
  '--color-info-100': brand.info[100],
  '--color-info-200': brand.info[200],
  '--color-info-300': brand.info[300],
  '--color-info-400': brand.info[400],
  '--color-info-500': brand.info[500],
  '--color-info-600': brand.info[600],
  '--color-info-700': brand.info[700],
  '--color-info-800': brand.info[800],
  '--color-info-900': brand.info[900],
  '--color-info-950': brand.info[950],

  '--color-primary-0': brand.primary[0],
  '--color-primary-50': brand.primary[50],
  '--color-primary-100': brand.primary[100],
  '--color-primary-200': brand.primary[200],
  '--color-primary-300': brand.primary[300],
  '--color-primary-400': brand.primary[400],
  '--color-primary-500': brand.primary[500], //this
  '--color-primary-600': brand.primary[600],
  '--color-primary-700': brand.primary[700],
  '--color-primary-800': brand.primary[800],
  '--color-primary-900': brand.primary[900],
  '--color-primary-950': brand.primary[950],

  '--color-secondary-0': brand.semantic.topPlatform[0],
  '--color-secondary-50': brand.semantic.topPlatform[50],
  '--color-secondary-100': brand.semantic.topPlatform[100],
  '--color-secondary-200': brand.semantic.topPlatform[200],
  '--color-secondary-300': brand.semantic.topPlatform[300],
  '--color-secondary-400': brand.semantic.topPlatform[400],
  '--color-secondary-500': brand.semantic.topPlatform[500],
  '--color-secondary-600': brand.semantic.topPlatform[600],
  '--color-secondary-700': brand.semantic.topPlatform[700],
  '--color-secondary-800': brand.semantic.topPlatform[800],
  '--color-secondary-900': brand.semantic.topPlatform[900],
  '--color-secondary-950': brand.semantic.topPlatform[950],

  '--color-tertiary-0': brand.semantic.genre[0],
  '--color-tertiary-50': brand.semantic.genre[50],
  '--color-tertiary-100': brand.semantic.genre[100],
  '--color-tertiary-200': brand.semantic.genre[200],
  '--color-tertiary-300': brand.semantic.genre[300],
  '--color-tertiary-400': brand.semantic.genre[400],
  '--color-tertiary-500': brand.semantic.genre[500],
  '--color-tertiary-600': brand.semantic.genre[600],
  '--color-tertiary-700': brand.semantic.genre[700],
  '--color-tertiary-800': brand.semantic.genre[800],
  '--color-tertiary-900': brand.semantic.genre[900],
  '--color-tertiary-950': brand.semantic.genre[950],
};

export const lightconfig = {
  '--color-typography-0': brand.typographyLight[0],
  '--color-typography-50': brand.typographyLight[50],
  '--color-typography-100': brand.typographyLight[100],
  '--color-typography-200': brand.typographyLight[200],
  '--color-typography-300': brand.typographyLight[300],
  '--color-typography-400': brand.typographyLight[400],
  '--color-typography-500': brand.typographyLight[500],
  '--color-typography-600': brand.typographyLight[600],
  '--color-typography-700': brand.typographyLight[700],
  '--color-typography-800': brand.typographyLight[800],
  '--color-typography-900': brand.typographyLight[900],
  '--color-typography-950': brand.typographyLight[950],

  '--color-outline-0': brand.outlineLight[0],
  '--color-outline-50': brand.outlineLight[50],
  '--color-outline-100': brand.outlineLight[100],
  '--color-outline-200': brand.outlineLight[200],
  '--color-outline-300': brand.outlineLight[300],
  '--color-outline-400': brand.outlineLight[400],
  '--color-outline-500': brand.outlineLight[500],
  '--color-outline-600': brand.outlineLight[600],
  '--color-outline-700': brand.outlineLight[700],
  '--color-outline-800': brand.outlineLight[800],
  '--color-outline-900': brand.outlineLight[900],
  '--color-outline-950': brand.outlineLight[950],

  '--color-background-0': brand.bgLight[0],
  '--color-background-50': brand.bgLight[50],
  '--color-background-100': brand.bgLight[100],
  '--color-background-200': brand.bgLight[200],
  '--color-background-300': brand.bgLight[300],
  '--color-background-400': brand.bgLight[400],
  '--color-background-500': brand.bgLight[500],
  '--color-background-600': brand.bgLight[600],
  '--color-background-700': brand.bgLight[700],
  '--color-background-800': brand.bgLight[800],
  '--color-background-900': brand.bgLight[900],
  '--color-background-950': brand.bgLight[950],

  '--color-background-error': brand.error[50],
  '--color-background-warning': brand.warning[50],
  '--color-background-success': brand.success[50],
  '--color-background-muted': brand.bgLight[50],
  '--color-background-info': brand.info[50],

  '--color-indicator-primary': brand.bgLight[950],
  '--color-indicator-info': brand.info[500],
  '--color-indicator-error': brand.error[500],
};

export const darkconfig = {
  '--color-typography-0': brand.typographyDark[0],
  '--color-typography-50': brand.typographyDark[50],
  '--color-typography-100': brand.typographyDark[100],
  '--color-typography-200': brand.typographyDark[200],
  '--color-typography-300': brand.typographyDark[300],
  '--color-typography-400': brand.typographyDark[400],
  '--color-typography-500': brand.typographyDark[500],
  '--color-typography-600': brand.typographyDark[600],
  '--color-typography-700': brand.typographyDark[700],
  '--color-typography-800': brand.typographyDark[800],
  '--color-typography-900': brand.typographyDark[900],
  '--color-typography-950': brand.typographyDark[950],

  '--color-outline-0': brand.outlineDark[0],
  '--color-outline-50': brand.outlineDark[50],
  '--color-outline-100': brand.outlineDark[100],
  '--color-outline-200': brand.outlineDark[200],
  '--color-outline-300': brand.outlineDark[300],
  '--color-outline-400': brand.outlineDark[400],
  '--color-outline-500': brand.outlineDark[500],
  '--color-outline-600': brand.outlineDark[600],
  '--color-outline-700': brand.outlineDark[700],
  '--color-outline-800': brand.outlineDark[800],
  '--color-outline-900': brand.outlineDark[900],
  '--color-outline-950': brand.outlineDark[950],

  '--color-background-0': brand.bgDark[0],
  '--color-background-50': brand.bgDark[50],
  '--color-background-100': brand.bgDark[100],
  '--color-background-200': brand.bgDark[200],
  '--color-background-300': brand.bgDark[300],
  '--color-background-400': brand.bgDark[400],
  '--color-background-500': brand.bgDark[500],
  '--color-background-600': brand.bgDark[600],
  '--color-background-700': brand.bgDark[700],
  '--color-background-800': brand.bgDark[800],
  '--color-background-900': brand.bgDark[900],
  '--color-background-950': brand.bgDark[950],

  '--color-background-error': brand.error[900],
  '--color-background-warning': brand.warning[900],
  '--color-background-success': brand.success[900],
  '--color-background-muted': brand.bgDark[900],
  '--color-background-info': brand.info[900],

  '--color-indicator-primary': brand.bgDark[50],
  '--color-indicator-info': brand.info[500],
  '--color-indicator-error': brand.error[500],
};

export const rawConfig = {
  light: { ...commonColors, ...lightconfig },
  dark: { ...commonColors, ...darkconfig },
};

export const config = {
  light: vars(rawConfig.light),
  dark: vars(rawConfig.dark),
};
