"""friendship_table

Revision ID: 07657a24706d
Revises: 
Create Date: 2026-08-04 10:33:04.279501

"""
from datetime import datetime
from typing import Sequence, Union
from uuid import UUID

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '07657a24706d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('game',
    sa.Column('steam_app_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_app_id')
    )
    op.create_index(op.f('ix_game_steam_app_id'), 'game', ['steam_app_id'], unique=False)
    op.create_table('user',
    sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('steam_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('steam_api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid'),
    sa.UniqueConstraint('steam_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_firebase_uid'), 'user', ['firebase_uid'], unique=False)
    op.create_index(op.f('ix_user_steam_id'), 'user', ['steam_id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)

    user_table = sa.table(
        'user',
        sa.column('id', sa.Uuid()),
        sa.column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(length=255)),
        sa.column('username', sqlmodel.sql.sqltypes.AutoString(length=100)),
        sa.column('steam_id', sqlmodel.sql.sqltypes.AutoString(length=32)),
        sa.column('steam_api_key', sqlmodel.sql.sqltypes.AutoString(length=255)),
    )
    op.bulk_insert(
        user_table,
        [
            {
                'id': UUID('11111111-1111-1111-1111-111111111111'),
                'firebase_uid': 'YLRMA6otQ1YDqHlD5j8Wr0u0lpJ2',
                'username': 'test-01',
                'steam_id': '76561198077919169',
                'steam_api_key': '724FF154B1D2A357857A257EA28C6415',
            },
            {
                'id': UUID('22222222-2222-2222-2222-222222222222'),
                'firebase_uid': 'tcYaHPGYDkVBlnNrcI7jNf2z4MS2',
                'username': 'test-02',
                'steam_id': '76561198000000002',
                'steam_api_key': '',
            },
            {
                'id': UUID('33333333-3333-3333-3333-333333333333'),
                'firebase_uid': 'GRbqhGIYlzb1GHEaBINeJq1ZXld2',
                'username': 'test-03',
                'steam_id': '76561198000000003',
                'steam_api_key': '',
            },
            {
                'id': UUID('44444444-4444-4444-4444-444444444444'),
                'firebase_uid': 'wcMFGsVqaYYNHSAeUXgGiK14WPk2',
                'username': 'test-04',
                'steam_id': '76561198000000004',
                'steam_api_key': '',
            },
            {
                'id': UUID('55555555-5555-5555-5555-555555555555'),
                'firebase_uid': 'a7swvzI0APgq57SMa8B7PsHevG02',
                'username': 'test-05',
                'steam_id': '76561198000000005',
                'steam_api_key': '',
            },
        ],
    )

    op.create_table('friendship',
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('addressee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendshipstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id')
    )

    friendship_table = sa.table(
        'friendship',
        sa.column('id', sa.Uuid()),
        sa.column('requester_id', sa.Uuid()),
        sa.column('addressee_id', sa.Uuid()),
        sa.column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendshipstatus')),
        sa.column('created_at', sa.DateTime()),
        sa.column('updated_at', sa.DateTime()),
    )
    now = datetime.now()
    op.bulk_insert(
        friendship_table,
        [
            {
                'id': UUID('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
                'requester_id': UUID('11111111-1111-1111-1111-111111111111'),
                'addressee_id': UUID('22222222-2222-2222-2222-222222222222'),
                'status': 'ACCEPTED',
                'created_at': now,
                'updated_at': now,
            },
            {
                'id': UUID('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
                'requester_id': UUID('44444444-4444-4444-4444-444444444444'),
                'addressee_id': UUID('11111111-1111-1111-1111-111111111111'),
                'status': 'PENDING',
                'created_at': now,
                'updated_at': now,
            },
            {
                'id': UUID('cccccccc-cccc-cccc-cccc-cccccccccccc'),
                'requester_id': UUID('11111111-1111-1111-1111-111111111111'),
                'addressee_id': UUID('55555555-5555-5555-5555-555555555555'),
                'status': 'BLOCKED',
                'created_at': now,
                'updated_at': now,
            },
        ],
    )

    op.create_table('shelving',
    sa.Column('status', sa.Enum('shelved', 'to_be_played', 'playing', 'played', 'platinato', name='game_status'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'game_id')
    )
    op.create_table('steamrollingtime',
    sa.Column('steam_app_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('last_day_playtime', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steamrollingtime_created_at'), 'steamrollingtime', ['created_at'], unique=False)
    op.create_index(op.f('ix_steamrollingtime_steam_app_id'), 'steamrollingtime', ['steam_app_id'], unique=False)
    op.create_index(op.f('ix_steamrollingtime_user_id'), 'steamrollingtime', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steamrollingtime_user_id'), table_name='steamrollingtime')
    op.drop_index(op.f('ix_steamrollingtime_steam_app_id'), table_name='steamrollingtime')
    op.drop_index(op.f('ix_steamrollingtime_created_at'), table_name='steamrollingtime')
    op.drop_table('steamrollingtime')
    op.drop_table('shelving')
    op.drop_table('friendship')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_steam_id'), table_name='user')
    op.drop_index(op.f('ix_user_firebase_uid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_game_steam_app_id'), table_name='game')
    op.drop_table('game')
    op.drop_table('config')
    # ### end Alembic commands ###
