"""friendship_table

Revision ID: 07657a24706d
Revises: 
Create Date: 2026-08-04 10:33:04.279501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '07657a24706d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('game',
    sa.Column('steam_app_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_app_id')
    )
    op.create_index(op.f('ix_game_steam_app_id'), 'game', ['steam_app_id'], unique=False)
    op.create_table('user',
    sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('steam_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('steam_api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid'),
    sa.UniqueConstraint('steam_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_firebase_uid'), 'user', ['firebase_uid'], unique=False)
    op.create_index(op.f('ix_user_steam_id'), 'user', ['steam_id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('friendship',
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('addressee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendshipstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id')
    )
    op.create_table('shelving',
    sa.Column('status', sa.Enum('shelved', 'to_be_played', 'playing', 'played', 'platinato', name='game_status'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'game_id')
    )
    op.create_table('steamrollingtime',
    sa.Column('steam_app_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('last_day_playtime', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steamrollingtime_created_at'), 'steamrollingtime', ['created_at'], unique=False)
    op.create_index(op.f('ix_steamrollingtime_steam_app_id'), 'steamrollingtime', ['steam_app_id'], unique=False)
    op.create_index(op.f('ix_steamrollingtime_user_id'), 'steamrollingtime', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steamrollingtime_user_id'), table_name='steamrollingtime')
    op.drop_index(op.f('ix_steamrollingtime_steam_app_id'), table_name='steamrollingtime')
    op.drop_index(op.f('ix_steamrollingtime_created_at'), table_name='steamrollingtime')
    op.drop_table('steamrollingtime')
    op.drop_table('shelving')
    op.drop_table('friendship')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_steam_id'), table_name='user')
    op.drop_index(op.f('ix_user_firebase_uid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_game_steam_app_id'), table_name='game')
    op.drop_table('game')
    op.drop_table('config')
    # ### end Alembic commands ###
