"""initial schema auto table names

Revision ID: 66b58bee0076
Revises:
Create Date: 2026-04-20 23:22:47.149318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66b58bee0076"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game",
        sa.Column("steam_app_id", sa.String(length=32), nullable=False),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("banner_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("steam_app_id"),
    )
    op.create_index(op.f("ix_game_steam_app_id"), "game", ["steam_app_id"], unique=False)
    op.create_table(
        "user",
        sa.Column("firebase_uid", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("steam_id", sa.String(length=32), nullable=False),
        sa.Column("steam_api_key", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("firebase_uid"),
        sa.UniqueConstraint("steam_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_user_firebase_uid"), "user", ["firebase_uid"], unique=False)
    op.create_index(op.f("ix_user_steam_id"), "user", ["steam_id"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    op.create_table(
        "shelving",
        sa.Column("status", sa.Enum("shelved", "to_be_played", "playing", "played", "platinato", name="game_status"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id", "game_id"),
    )
    op.create_table(
        "steamrollingtime",
        sa.Column("steam_app_id", sa.String(length=32), nullable=False),
        sa.Column("last_day_playtime", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_steamrollingtime_created_at"), "steamrollingtime", ["created_at"], unique=False)
    op.create_index(op.f("ix_steamrollingtime_steam_app_id"), "steamrollingtime", ["steam_app_id"], unique=False)
    op.create_index(op.f("ix_steamrollingtime_user_id"), "steamrollingtime", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_steamrollingtime_user_id"), table_name="steamrollingtime")
    op.drop_index(op.f("ix_steamrollingtime_steam_app_id"), table_name="steamrollingtime")
    op.drop_index(op.f("ix_steamrollingtime_created_at"), table_name="steamrollingtime")
    op.drop_table("steamrollingtime")
    op.drop_table("shelving")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_steam_id"), table_name="user")
    op.drop_index(op.f("ix_user_firebase_uid"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_game_steam_app_id"), table_name="game")
    op.drop_table("game")
    # ### end Alembic commands ###
