"""initial_schema

Revision ID: 864b339f1bac
Revises:
Create Date: 2026-09-04 00:56:21.589890

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "864b339f1bac"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "game",
        sa.Column("steam_app_id", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("steam_app_id"),
    )
    op.create_index(op.f("ix_game_steam_app_id"), "game", ["steam_app_id"], unique=False)
    op.create_table(
        "genre",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "topgame",
        sa.Column("steam_app_id", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_topgame_rank"), "topgame", ["rank"], unique=False)
    op.create_index(op.f("ix_topgame_steam_app_id"), "topgame", ["steam_app_id"], unique=True)
    op.create_table(
        "user",
        sa.Column("firebase_uid", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("steam_id", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("steam_api_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("firebase_uid"),
        sa.UniqueConstraint("steam_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_user_firebase_uid"), "user", ["firebase_uid"], unique=False)
    op.create_index(op.f("ix_user_region"), "user", ["region"], unique=False)
    op.create_index(op.f("ix_user_steam_id"), "user", ["steam_id"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    op.create_table(
        "devicetoken",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devicetoken_device_token"), "devicetoken", ["device_token"], unique=True)
    op.create_index(op.f("ix_devicetoken_user_id"), "devicetoken", ["user_id"], unique=False)
    op.create_table(
        "friendship",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("addressee_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "ACCEPTED", "BLOCKED", name="friendshipstatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["addressee_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("requester_id", "addressee_id"),
    )
    op.create_table(
        "gamegenrelink",
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("genre_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genre.id"],
        ),
        sa.PrimaryKeyConstraint("game_id", "genre_id"),
    )
    op.create_table(
        "notification",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notification_is_read"), "notification", ["is_read"], unique=False)
    op.create_index(op.f("ix_notification_user_id"), "notification", ["user_id"], unique=False)
    op.create_table(
        "shelving",
        sa.Column("status", sa.Enum("shelved", "to_be_played", "playing", "platinato", name="game_status"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id", "game_id"),
    )
    op.create_table(
        "steamrollingtime",
        sa.Column("steam_app_id", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("last_day_playtime", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_steam_rolling_time_user_id_created_at", "steamrollingtime", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_steamrollingtime_created_at"), "steamrollingtime", ["created_at"], unique=False)
    op.create_index(op.f("ix_steamrollingtime_steam_app_id"), "steamrollingtime", ["steam_app_id"], unique=False)
    op.create_index(op.f("ix_steamrollingtime_user_id"), "steamrollingtime", ["user_id"], unique=False)
    op.create_table(
        "topgamegenrelink",
        sa.Column("top_game_id", sa.Uuid(), nullable=False),
        sa.Column("genre_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genre.id"],
        ),
        sa.ForeignKeyConstraint(
            ["top_game_id"],
            ["topgame.id"],
        ),
        sa.PrimaryKeyConstraint("top_game_id", "genre_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("topgamegenrelink")
    op.drop_index(op.f("ix_steamrollingtime_user_id"), table_name="steamrollingtime")
    op.drop_index(op.f("ix_steamrollingtime_steam_app_id"), table_name="steamrollingtime")
    op.drop_index(op.f("ix_steamrollingtime_created_at"), table_name="steamrollingtime")
    op.drop_index("idx_steam_rolling_time_user_id_created_at", table_name="steamrollingtime")
    op.drop_table("steamrollingtime")
    op.drop_table("shelving")
    op.drop_index(op.f("ix_notification_user_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_is_read"), table_name="notification")
    op.drop_table("notification")
    op.drop_table("gamegenrelink")
    op.drop_table("friendship")
    op.drop_index(op.f("ix_devicetoken_user_id"), table_name="devicetoken")
    op.drop_index(op.f("ix_devicetoken_device_token"), table_name="devicetoken")
    op.drop_table("devicetoken")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_steam_id"), table_name="user")
    op.drop_index(op.f("ix_user_region"), table_name="user")
    op.drop_index(op.f("ix_user_firebase_uid"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_topgame_steam_app_id"), table_name="topgame")
    op.drop_index(op.f("ix_topgame_rank"), table_name="topgame")
    op.drop_table("topgame")
    op.drop_table("genre")
    op.drop_index(op.f("ix_game_steam_app_id"), table_name="game")
    op.drop_table("game")
    op.drop_table("config")
    # ### end Alembic commands ###
