name: Jest Tests

on:
  pull_request: null

permissions: {}

jobs:
  test:
    runs-on: self-hosted
    permissions:
        contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: mobile-app/package-lock.json

      - name: Install dependencies
        working-directory: mobile-app
        run: npm ci

      - name: Run Jest tests with coverage
        working-directory: mobile-app
        run: npx jest --ci